# Generated by Django 3.1.7 on 2021-02-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210224_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wish_product',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
