# Generated by Django 3.1.7 on 2021-03-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_wish_emailaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitem',
            name='active',
        ),
        migrations.AddField(
            model_name='wishitem',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
