# Generated by Django 3.1.7 on 2021-03-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0004_remove_wishitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitem',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
    ]
